name: Build CV and Push PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up TeX Live + Python
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex texlive-latex-base texlive-latex-recommended

      - name: Install Times New Roman font
        run: |
          sudo apt-get install software-properties-common -y
          sudo add-apt-repository multiverse -y
          sudo apt-get update

          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer -y

          sudo fc-cache -f -v
          

      - name: verify fonts
        run: |
          ls /usr/share/fonts/truetype/msttcorefonts
          fc-list | grep "Times New Roman" || echo "Font not found"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Build PDF
        run: source build.sh

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: out/CV.pdf

      - name: Checkout TARGET repository
        uses: actions/checkout@v4
        with:
          repository: ShayanHaghighi/portfolio
          token: ${{ secrets.CV_UPDATER }}
          path: portfolio

      - name: Push to external repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cd portfolio

          # copy the PDF
          cp ../out/CV.pdf ./public/CV.pdf

          # commit and push
          git add ./public/CV.pdf
          git commit -m "Update CV PDF (bot)"
          git push
